name: Validate code with branhces

on:
  push:
    paths:
      # Any push changes in the infrastructure
      - 'abwatne-oppg2/abwatne-oppg2/azure-terraform-project/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  WORKING_DIR: ./abwatne-oppg2/abwatne-oppg2/azure-terraform-project/

jobs:
  # Job for format checking the code
  fmt_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Move to dev branch 
        run: git checkout -b dev
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select or create dev
        run: terraform workspace select dev || terraform workspace new dev
        working-directory: ${{ env.WORKING_DIR }}
    
      - name: Terraform fmt
        run: terraform fmt -recursive
        working-directory: ${{ env.WORKING_DIR }}

  # Job for validate checking the code
  # This will happen in the default workflow, but in a branch other than main
  validate_check:
    #needs: fmt_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Move to dev branch 
        run: git checkout -b dev
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select or create dev
        run: terraform workspace select dev || terraform workspace new dev
        working-directory: ${{ env.WORKING_DIR }}
    
      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
  
  tfsec_check:
    needs: validate_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: tfsec

      # You may pin to the exact commit or the version.
      #uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          # Directory to run the action on, from the repo root. Default is . (root of the repository)
          working_directory: ${{ env.WORKING_DIR }}
          github_token: ${{ env.GITHUB_TOKEN }}
          args: --concise-output #--minimum-severity CRITICAL --minimum-severity HIGH --minimum-severity MEDIUM --include-ignored
