name: Init and apply on pull

on:
  pull_request:
    branches: [ staging ]
    types: [closed]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./abwatne-oppg2/abwatne-oppg2/azure-terraform-project/

jobs:
  dev_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      #- name: Move to dev branch 
      #  run: git checkout dev || git checkout -b dev
      #  working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform workspace select or create dev
        run: terraform workspace select dev || terraform workspace new dev
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan -var-file='abwatne-oppg2/azure-terraform-project/terraform.tfvars.dev' -out='main.tfplan'
      
      - name: Terraform apply dev
        run: terraform apply -out='main.tfplan' -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
      #- name: Push to staging branch
      #  run: git push origin staging
      #  working-directory: ${{ env.WORKING_DIR }}
        
    #paths:
      # Any pulls in the infrastructure
      #- 'abwatne-oppg2/abwatne-oppg2/azure-terraform-project/**'
     #workflow_dispatch:
     
