name: Init and apply on pull

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - dev
    #paths:
      # Any pulls in the infrastructure
      #- 'abwatne-oppg2/abwatne-oppg2/azure-terraform-project/**'
     #workflow_dispatch:
     
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./abwatne-oppg2/abwatne-oppg2/azure-terraform-project/

jobs:
  merge_dev_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Move to staging branch
        run: git checkout staging || git checkout -b staging
        working-directory: ${{ env.WORKING_DIR }}

      - name: Merge dev -> staging
        run: git merge dev
        working-directory: ${{ env.WORKING_DIR }}

      - name: Push to staging branch
        run: git push origin staging
        working-directory: ${{ env.WORKING_DIR }}
