name: Merge into staging and apply infra

on:
  pull_request:
    branches: [ staging ]
    types: [closed]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./abwatne-oppg2/abwatne-oppg2/azure-terraform-project/deployments

jobs:
  staging_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform workspace select or create staging
        run: terraform workspace select staging || terraform workspace new staging
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan -var-file='terraform.tfvars.staging' -out='main.tfplan'
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Terraform apply staging
        run: terraform apply -auto-approve "main.tfplan"
        working-directory: ${{ env.WORKING_DIR }}
     
